### PR TITLE
minor changes needed to make today's DSP patch work again.

### LINKED ISSUE #29: Error with latest update
Getting this error constantly with game version 0.10.28.21150 mod version 0.8.5

```
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type UIStatisticsWindow and name entriesLen
System.ArgumentException: FieldRefAccess<UIStatisticsWindow, System.Int32> for Statistics Window (UIStatisticsWindow), entriesLen caused an exception ---> System.MissingFieldException: Field 'UIStatisticsWindow.entriesLen' not found.
  at HarmonyLib.AccessTools.GetInstanceField (System.Type type, System.String fieldName) [0x00010] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0 
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00032] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00092] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0 
  at LSTMMod.UIStatisticsWindowAgent.PostCreate () [0x00023] in <b48996803f5644cbbb92da04353e603c>:0 
  at LSTMMod.LSTM+Patch.UIGame__OnCreate_Postfix () [0x0003f] in <b48996803f5644cbbb92da04353e603c>:0 
  at UIGame._OnCreate () [0x003c9] in <c3b295ce06254256906510939c4119d1>:0 
  at ManualBehaviour._Create () [0x00030] in <c3b295ce06254256906510939c4119d1>:0 
```

```
NullReferenceException: Object reference not set to an instance of an object
  at LSTMMod.LSTM+Patch.Mod_entitySignPool_Postfix (EntitySignRenderer __instance) [0x00007] in <b48996803f5644cbbb92da04353e603c>:0 
  at EntitySignRenderer.Draw () [0x00099] in <c3b295ce06254256906510939c4119d1>:0 
  at FactoryModel.OnCameraPostRender (UnityEngine.Camera cam) [0x000d9] in <c3b295ce06254256906510939c4119d1>:0 
  at (wrapper delegate-invoke) System.Action`1[UnityEngine.Camera].invoke_void_T(UnityEngine.Camera)
  at MainCamera.OnPostRender () [0x00007] in <c3b295ce06254256906510939c4119d1>:0 
```

### LINKED ISSUE #30: Error starting DSP
Hi, I'm getting this error message when opening the game.

This error started happening today, I didn't change any mods from yesterday to today

[Error  : Unity Log] System.ArgumentException: FieldRefAccess<UIStatisticsWindow, System.Int32> for Statistics Window (UIStatisticsWindow), entriesLen caused an exception ---> System.MissingFieldException: Field 'UIStatisticsWindow.entriesLen' not found.
  at HarmonyLib.AccessTools.GetInstanceField (System.Type type, System.String fieldName) [0x00010] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00032] in <474744d65d8e460fa08cd5fd82b5d65f>:0
   --- End of inner exception stack trace ---
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00092] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at LSTMMod.UIStatisticsWindowAgent.PostCreate () [0x00023] in <b48996803f5644cbbb92da04353e603c>:0
  at LSTMMod.LSTM+Patch.UIGame__OnCreate_Postfix () [0x0003f] in <b48996803f5644cbbb92da04353e603c>:0
  at UIGame._OnCreate () [0x003c9] in <c3b295ce06254256906510939c4119d1>:0
  at ManualBehaviour._Create () [0x00030] in <c3b295ce06254256906510939c4119d1>:0

### PR DESCRIPTION
**Pull request by geeksville**
I'm a novice modder and haven't written any C# for a long time.  But seems to be a good fix on my machine.  If useful here's a fix @hetima.

Probably not cool for me to send out my built dll.  So I presume others will need to wait for Hetima's review and possible release.

### CODE REVIEW

**Comment by geeksville** [comment]
fix #29 (to have github tag correctly)

**Comment by geeksville** [comment]
fix #30

**Comment by alnet** [comment]
This looks like it would work, though I haven't touched c# in ages. What's needed to build it these days? If I can build it locally I'll build it took for at least another person to test.

**Comment by geeksville** [comment]
@alnet it definitely works ;-)

Here's a temporary dll to hold you over (usual caveats about trusting binaries from strangers tho ;-)) 
[LSTM.zip](https://github.com/hetima/DSP_LSTM/files/13796243/LSTM.zip)

**Comment by geeksville** [comment]
but in theory (at least on my linux machine) the only thing needed to build is to cd into the dir and "dotnet build".  I used dotnet 7.0

**Comment by alnet** [comment]
> but in theory (at least on my linux machine) the only thing needed to build is to cd into the dir and "dotnet build". I used dotnet 7.0

Oh I hadn't touched C# since the dotnet on linux thing either. I had no idea it could cross build, that's very cool and I'll give it a shot, specifically because of binaries from strangers. :) Thanks for the info in any case!

**Comment by alnet** [comment]
> > but in theory (at least on my linux machine) the only thing needed to build is to cd into the dir and "dotnet build". I used dotnet 7.0
> 
> Oh I hadn't touched C# since the dotnet on linux thing either. I had no idea it could cross build, that's very cool and I'll give it a shot, specifically because of binaries from strangers. :) Thanks for the info in any case!

Forgot to add, compiling locally in linux for me as well, few hours of game time now with no further issues, so for everyone else monitoring this PR, you can install linux ubuntu in a vm and build this branch yourself all for free if you don't want to figure out windows build environment, or use the provided dll if you trust a binary from internet strangers. :D

**Comment by hetima** [comment]
thanks!

**Comment by Thilenios** [comment]
Will you be pushing this out to the store page? I use R2modman and have no idea how to do it manually haha

**Comment by hetima** [comment]
0.8.6 released

**Comment by geeksville** [comment]
thanks again for making this @hetima !

**Pull request merged**
